# Generated by Django 3.2 on 2022-01-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='app1/img/category', verbose_name='thumbnail')),
                ('desc', models.TextField()),
            ],
        ),
    ]
