# Generated by Django 3.2 on 2022-01-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='pot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('loc', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('cat', models.CharField(max_length=200)),
                ('thumb', models.ImageField(upload_to='app1/img/post/thumb', verbose_name='thumb')),
            ],
        ),
    ]
