# Generated by Django 3.2 on 2022-01-23 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_pot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pot',
            new_name='post',
        ),
    ]
