# Generated by Django 3.2 on 2022-01-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_pot_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='afrom',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='ato',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
