# Generated by Django 3.2 on 2022-01-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20220124_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(default='def', max_length=200),
        ),
    ]
