# Generated by Django 3.2 on 2022-01-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='user',
            field=models.CharField(default=' ', max_length=150),
            preserve_default=False,
        ),
    ]
