# Generated by Django 3.2 on 2022-01-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_post_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='post',
        ),
        migrations.AddField(
            model_name='proposal',
            name='post',
            field=models.ManyToManyField(default=1, to='app1.post'),
        ),
    ]
