# Generated by Django 3.2 on 2022-01-24 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20220125_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='post',
        ),
        migrations.AddField(
            model_name='proposal',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.post'),
        ),
    ]
