# Generated by Django 3.2 on 2022-02-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_proposal_mob'),
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=500)),
                ('msg', models.CharField(max_length=1000)),
                ('star', models.IntegerField()),
            ],
        ),
    ]
